name: Upload
on:
  push:
    branches:
      - main
env:
 JFROG_NAMESPACE: "cloudops"
 JF_URL: ${{ secrets.ARTIFACTORY_URL }}
 JF_ACCESS_TOKEN: ${{ secrets.TOKEN }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.S3 }}
    defaults:
      run:
        working-directory: ./s3
  upload:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    outputs:
    defaults:
      run:
        working-directory: ./s3

    steps:
      - name: checkout
        uses: actions/ceckout@v4
      - name: changes
        uses: dorney/paths-filter@v3
        id: changes
        with:
          filters: |
            s3:
              - './s3/VERSION.txt'
      - name: setup
        uses: jfrog/setup-jfrog-cli@v3
      - name: config
        run: 
          export SERVER_ID="wema"
          jf c add $SERVER_ID --url=$JF_URL --access-token=$JF_ACCESS_TOKEN --interactive=false
          jf tfc --server-id-deploy $SERVER_ID --repo-deploy terraform-local-modules
          jf tf p --nmaespace=${JFROG_NAMESPACE} --provider=local --tag=$(cat VERSION.txt)
        
  
